### ISSUE TITLE
`ci/check-basic-style.sh`: ignore trailing whitespace in comments

### ISSUE THREAD

**Issue by SWW13** [htwg-syslab-bsys/bsys-ss17-homework#14]

**Comment by mmaechtel** [comment]
Hmm, no style guide for comments, i' m not sure about comments in e.g std lib ...

**Comment by SWW13** [comment]
At least for documentation strings `//!` and `///` they should be ignored as they are written in markdown. (see https://doc.rust-lang.org/book/documentation.html#documenting-source-code)
Markdown uses double trailing white space for new line.

**Comment by mmaechtel** [comment]
Yes, that's right. Could you change the tests to take this into account? Then we can update the tests tomorrow (before the lab schedule) for all groups.

**Comment by mmaechtel** [comment]
no problem, python is installed in 2.7er version

**Comment by mmaechtel** [comment]
ahh, what about travis? I uses shell skripts, since they work mostly out of the box. Don't knwo how long travis checks are prolonged by python install ...

**Comment by SWW13** [comment]
maybe they have python preinstalled, will test that

**Comment by mmaechtel** [comment]
hopefully

**Comment by mmaechtel** [comment]
i hope its installed, not that i hope you test ist :D

**Comment by SWW13** [comment]
python works out of the box with our current `.travis.yml`, see https://travis-ci.org/SWW13/bsys-ss17-homework/builds/215499259#L162

**Comment by mmaechtel** [comment]
👍
