### ISSUE TITLE
`output.bats` failes when path contains spaces

### ISSUE THREAD

**Issue by hekrause** [htwg-syslab-bsys/bsys-ss17-homework#18]
@SWW13 
Ich hab mein Repository in einem Ordner der ../Dokumente/HTWG Konstanz 5.Semester/....Repository heißt.
Das Skript kommt mit den Leerzeichen im Ordnername HTWG Konstanz 5.Semester nicht zurecht und escaped die nicht.
Wenn ich mein Repository nach /home/henning/ kopiere funktioniert das Ganze.

Also falls jmd. den Fehler hat dann Hilft das als Hinweis vllt.

![bildschirmfoto vom 2017-03-31 13-05-38](https://cloud.githubusercontent.com/assets/17926729/24547961/d511b3a4-1612-11e7-97c9-6c57b3c93930.png)

**Comment by SWW13** [comment]
Der Fehler liegt in den `output.bats` Dateien und sollten mit dem Pull Request #19 gefixed sein.

**Comment by hekrause** [comment]
Okay dann man schaun^^ ich teste das dann wenn der PR durch ist und meld mich wieder.

**Comment by SWW13** [comment]
Du kannst es auch direkt testen: https://github.com/SWW13/bsys-ss17-homework/tree/fixed_bats
Dann kann ich falls es nicht tut das ganze nochmal anpassen ;)

**Comment by mmaechtel** [comment]
#19 merged
