### ISSUE TITLE
parse_config() ?

### ISSUE THREAD

**Issue by hekrause** [htwg-syslab-bsys/bsys-ss17-homework#22]
@SWW13 
Welche parse_config() Methode ist denn hier in task2 gemeint?
Oder ist da vllt. parse_arguments() gemeint?
https://github.com/htwg-syslab-bsys/bsys-ss17-homework/tree/master/hw2/task2

**Comment by mmaechtel** [comment]
ups, *parse_arguments()* ist gemeint, habs verbessert! Danke!
