### ISSUE TITLE
Task2 Output.bats

### ISSUE THREAD

**Issue by hekrause** [htwg-syslab-bsys/bsys-ss17-homework#25]
@mmaechtel @SWW13 @htwg-syslab-bsys/tutor

Die tests aus task2 laufen alle positiv durch nur wenn man das output.bats mit
```
bats outputbats.bats
```
ausführt kommen Meldungen das die executable in /target/debug/ nicht gefunden werden konnte.
Bei task1 funktioniert das aber alle ohne Probleme.
![bildschirmfoto vom 2017-04-09 21-47-23](https://cloud.githubusercontent.com/assets/17926729/24840487/49d78012-1d6e-11e7-9f7c-6fd58de07c54.png)

Gibt es da etwas das man noch in main.rs, lib.rs oder in der test2.rs eintragen müsste?

**Comment by mmaechtel** [comment]
1.) Ist das target/debug/task2 vorhanden?
2.) Was sagt der Test in Ihrer Workstation (Referenz?)

**Comment by hekrause** [comment]
Es existieren zwei executables mit den Namen task2-146238a52dfe511d* und task2-1948d4ef763b3328*

Im Container passiert genau das Gleiche.

**Comment by mmaechtel** [comment]
zu output.bats: Ändern Sie doch bitte mal in der Datei:
`ci/test-bats.sh`in Zeile 16 das Kommando 'cargo run' in 'cargo build'. Dann sollten alle Tests laufen ...

Das mit den seltsamen executable Namen kann ich leider bei mir noch nicht nachstellen ....

**Comment by hekrause** [comment]
Okay jetzt läuft task1 durch ohne Fehler. Es war Zeile 19.
Soll ich dann mit dem Pull Request noch warten oder soll ich den schon einreichen?

**Comment by mmaechtel** [comment]
ah ok, hab schon ne neuere Variante dieses Skripts, daher der Zeilendreher.

Laufen mit dieser Änderung jetzt komplett alle Tests, oder wo hängt bei Ihnen der `ci/run-all.s ?

**Comment by hekrause** [comment]
Das task2 output.bats läuft nicht durch:
![grafik](https://cloud.githubusercontent.com/assets/17926729/24841310/2f229ca2-1d82-11e7-9b1c-d88a959c189a.png)

Anscheinend findet er das task2* nicht....in task1 läuft genau dieses output.bats ohne Probleme durch.

**Comment by hekrause** [comment]
Ah jetzt habe ich etwas:
![grafik](https://cloud.githubusercontent.com/assets/17926729/24841354/d9c4c928-1d82-11e7-864e-8f681710e63b.png)
Im Container hat er das Problem nicht das er die Executables nicht findet.
Dort gibt es aber auch nur die beiden task2 Versionen mit dem Längerem Namen...

**Comment by mmaechtel** [comment]
das cargo build in task2 erstellt ein `target/debug/task2`. Das benutzt dann der output.bats Test. Wenn das nicht findet beschwert er sich.

Könnte bei Ihnen ein Sonderzeichen Problem im Pfad sein. Probieren Sie dochmal einen Pfad ohne Sonderzeichen (also ohne ein ä oder Leerzeichen). Evtl. müssen wir da noch an den Skripten basteln, dass die zu keinen Fehler führt.

**Comment by mmaechtel** [comment]
wie gesagt, nehmen Sie mal nen anderen Pfad, Sie haben derzeit:
... Betriebssystem(Mächtel) ... im Pfad.

Am besten mal direkt in Ihrem home das Repo auspacken und testen

**Comment by mmaechtel** [comment]
also direkt unter z.B. `/media/henning/repotest` oder sowas in der Art

**Comment by hekrause** [comment]
Ja genau ich hab das mal in /home/Henning/tmp/ ausprobiert...aber das hatte auch keinen Effekt...

**Comment by hekrause** [comment]
Ich hab den "Fehler". @mmaechtel 
Ich hatte folgendes zur Cargo.toml hinzugefügt damit "cargo doc" durchläuft:
```
...
[bin]]
-doc = true
-name = "main"
-path = "src/main.rs"
...
```
Ohne die paar Zeilen läuft er durch.
Ich hatte das hinzugefügt weil ich beim "cargo doc" erstellen immer folgendne Fehler bekommen hatte:
![grafik](https://cloud.githubusercontent.com/assets/17926729/24852423/b2c0b012-1dd7-11e7-959b-26e096b06968.png)

**Comment by SWW13** [comment]
@hekrause Du warst wohl schneller.

Fehler war das in der `Cargo.toml` ein anderer binary name angegeben war:
```toml
[[bin]]
doc = true
name = "main"
path = "src/main.rs"
```

**Comment by mmaechtel** [comment]
👍

**Comment by SWW13** [comment]
Workaround for `cargo doc`:

```toml
[[bin]]
doc = false
name = "task2"
```

**Comment by mmaechtel** [comment]
sollte noch in die Doku oder?

**Comment by SWW13** [comment]
Wäre sicherlich hilfreich, eventuell sollten wir in Zukunft auch die Aufgaben anpassen damit `bin` und `lib` unterschiedliche Namen haben.

**Comment by mmaechtel** [comment]
muss ich mal tüfteln, wie ich dann in tests/task2.rs die Tests aufrufe ....

**Comment by mmaechtel** [comment]
fixed in #29

**Comment by mmaechtel** [comment]
# mentioned in #30
