### ISSUE TITLE
Fehler in test-bats.sh

### ISSUE THREAD

**Issue by hekrause** [htwg-syslab-bsys/bsys-ss17-homework#26]
@SWW13 @mmaechtel  @htwg-syslab-bsys/tutor 
Beim Ausführen des Befehls ./ci/run-all.sh läuft das Skript(unabhängig von https://github.com/htwg-syslab-bsys/bsys-ss17-homework/issues/25) nicht ganz durch Obwohl alle tests positiv sind.
![bildschirmfoto vom 2017-04-09 22-27-04](https://cloud.githubusercontent.com/assets/17926729/24840761/ee62ede2-1d73-11e7-9dcc-8a5133658187.png)
Das liegt daran das im Skript test-bats.sh in Zeile 19 jede Task einmal ohne Argumente aufgerufen wird und dann Fehlschlägt. Wenn man die Zeile Auskommentiert dann läuft das Skript bis zum Fehler aus https://github.com/htwg-syslab-bsys/bsys-ss17-homework/issues/25.
![bildschirmfoto vom 2017-04-09 22-24-15](https://cloud.githubusercontent.com/assets/17926729/24840777/5480743c-1d74-11e7-810c-a345451b880a.png)

**Comment by mmaechtel** [comment]
Den 'ohne Argumente' Fall müssen wir noch ins Fehlerskript korrekt einbauen

**Comment by SWW13** [comment]
Fixed in 766f774e39dfb8c8cf4479ee2961d9723a49836d and cherry-picked into all group repos.
