### ISSUE TITLE
Add Cargo.lock

### ISSUE THREAD

**Issue by SWW13** [htwg-syslab-bsys/bsys-ss17-homework#3]
Adding Cargo.lock to version control is recommended according to the [FAQ](http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries):
> As a result, it is recommended that all binaries check in their Cargo.lock.

**Comment by mmaechtel** [comment]
hmmm, missed to change this, after switching in homeworks to binaries ... ok will update homework and template for student repos

**Comment by SWW13** [comment]
fixed in 5ca3807c87de8b5531414ea9156b115c60f34bdf, 5d8dcb48d7979be9895e6e9e4bf3e395631b39a4

**Comment by mmaechtel** [comment]
also fixed in docu with  5d8dcb48d7979be9895e6e9e4bf3e395631b39a4 and a608e45164cde0eda08a6f207421d3242cbb0600
