### ISSUE TITLE
Base instead of bounds?

### ISSUE THREAD

**Issue by kedeggel** [htwg-syslab-bsys/bsys-ss17-homework#32]
Hw3 Simu1 question 2:
In the original homework in the book it's asked for the max value that BASE can be set to (here BOUNDS)

**Comment by mmaechtel** [comment]
BASE makes more sense! Seemed to have changed in v0.92 of the book. My version of the book is outdated :-/ But I double check with the author if it is a typo ... to be sure.

**Comment by mmaechtel** [comment]
Fixed in master now

**Comment by mmaechtel** [comment]
Please let it be opened during hw3 ... so others can read it as well :-)
