### ISSUE TITLE
Update forks with merge or rebase

### ISSUE THREAD

**Issue by SWW13** [htwg-syslab-bsys/bsys-ss17-homework#4]
Possibility to update forked repositories with merge or rebase should at least be mentioned in [OVERVIEW.md](https://github.com/htwg-syslab-bsys/bsys-ss17-homework/blob/master/OVERVIEW.md#neue-aufgabenstellung).

```
$ git clone git@github.com:SusiSorglos/bsys-ss17-grp0.git
$ cd bsys-ss17-grp0
$ git remote add upstream https://github.com/htwg-syslab-bsys/bsys-ss17-homework.git

$ git fetch upstream
$ git checkout master
$ git rebase upstream master
```

**Comment by mmaechtel** [comment]
the idea is, to put this info into a task for homework 1, since during homework1 the pull request will be accepted and an update must be done. Except we find a lot of more missing parts in the docu ;-)

**Comment by mmaechtel** [comment]
I already moved some info of upstream merging into task1 of hw0. Should we give more examples than the link into the github documentation? Perhaps a small example?

**Comment by SWW13** [comment]
Maybe a live demo on tuesday?

**Comment by mmaechtel** [comment]
I didn't mention rebase in my git intro but merge, so the example could be:
```
$ git remote add upstream https://github.com/htwg-syslab-bsys/bsys-ss17-grpN.git
$ git fetch upstream
$ git checkout master
$ git merge upstream master
```
hmmm let's see if we could show this in http://learngitbranching.js.org

**Comment by SWW13** [comment]
lgtm

We should also mention rebase and the basic idea of rebase (maybe later?). Many projects require squashing pull requests into few as possible commits without merge commits.

**Comment by mmaechtel** [comment]
Would you like to give a short demo, maybe on

http://learngitbranching.js.org

**Comment by SWW13** [comment]
I pushed the new ci scripts to all repositories (script used: https://github.com/htwg-syslab-bsys/bsys-ss17-ci/pull/3).

I can do a short demo tomorrow.

**Comment by mmaechtel** [comment]
Great!

**Comment by mmaechtel** [comment]
Should we document the demo?
