### ISSUE TITLE
Topics for next BSYS Lab

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab-bsys/bsys-ss17-homework#6]
### In Lab:
- [ ]  who assigns reviewer (the student)
- [ ]  who to use '@' to address someone in an issue. Special tag  'htwg-syslab-bsys/tutor'
- [ ]  who deletes branches of accepted PR (the student)
- [ ] `Tipp` and `Hint` meanings in PR

- [ ] Students move to another group: Which steps do they have to do
     - Moodle: change group, then go to HJ to get access to new workstation
     - send email to bsys tutor with info about group change and:
               - gitid
               - old group
               - new group

### Internal:
- [ ]  Gradings, where and how to update (InProgress)

**Comment by mmaechtel** [comment]
or we pick the PR's an assign oneself ....

**Comment by mmaechtel** [comment]
in travis not all tests are checked, so running them in local repo?

**Comment by SWW13** [comment]
Reviewer can only be set to persons (at least when i tried it), but you can set multiple reviewers.
I would appreciate if students can select a reviewer (as a wish) and if that does not fit we can still change the reviewer. This would enable the students to select the tutor they already talked about their problems.

I'm automatically watching all group repositories (seems to be the default setting), so for me there is no need for mentions. But also nothing that speaks against mentions.

I'm working on some scripts to automate this, see [bsys-ss17-ci](https://git.brn.li/htwg-syslab-bsys/bsys-ss17-ci) and the [fetch-pr.sh](https://git.brn.li/htwg-syslab-bsys/bsys-ss17-ci/blob/master/scripts/fetch-pr.sh)-script.
(currently a tried running the tests on my own gitlab instance)

**Comment by mmaechtel** [comment]
OK, i don't have this default so I fiddle with github config this evening ;-)

ahh, this is the way to get the PR's 👍 (fetch-pr.sh) GREAT!!

**Comment by mmaechtel** [comment]
Should we delete the reviewed and accepted PR`s ?

**Comment by SWW13** [comment]
I don't think this is a good practice and we should try to set good example.

**Comment by mmaechtel** [comment]
👍

**Comment by mmaechtel** [comment]
.. ah I meant the branches, not the PR itself ... sorry

**Comment by SWW13** [comment]
Oh, then they can be deleted. But as they are on the forked repository the students should do this themselves if they wish to do so.

**Comment by mmaechtel** [comment]
OK, next ToDo Topic to mention on Tuesday ;-) I add a list of topics at the top of this issue

**Comment by mmaechtel** [comment]
the `fetch-pr` script adds the .gitlab-ci.yml file. So it could one day also run with github ci (travis) as well? Also by this we could add and change a file like "GRADING.md", where we add the points for each homework, right?

**Comment by SWW13** [comment]
Sure, I still play around with the automation scripts.

I don't think automating an `GRADING.md` file wouldn't be easy with all the possible edge cases, at least with batch.

**Comment by mmaechtel** [comment]
The content of GRADING.md will be changed by us 'by hand' , but new files like the GRADING.md and ci/ stuff could be deployed by your script. After the merge or rebase its in each individual group repo. 
But the general question is, where to store the gradings? In a file like the above GRADING.md or in the wiki of each group repo?

**Comment by SWW13** [comment]
That would work. Updating the wiki could also be done by a script, since it's also a git repository.

I need to think about that.

**Comment by SWW13** [comment]
Please add `Tipp`and `Hint`-meaning in pull requests to the topics list.

**Comment by mmaechtel** [comment]
added some more info into the wiki ....
