### ISSUE TITLE
./ci/check-basic-style.sh: 'gwc' not found  (on darwin systems)

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab-bsys/bsys-ss17-homework#9]
which brew package am I missing on my darwin (mac) systems?

Do we have to change bats scripts in tests/ ?

**Comment by SWW13** [comment]
```
brew install coreutils
```
`coreutils` contains most gnu compatible utils under OS X with the prefix `g`.

The bats test scripts look fine so far.
